export default {
  box: {
    display: 'flex',
    position: 'relative',
    alignItems: 'flex-start',
    flexDirection: 'column',
    backgroundColor: '#ffffff',
    width: '750px',
    height: '2202px',
  },
  hd: {
    boxSizing: 'border-box',
    display: 'flex',
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: '3px',
    paddingRight: '25px',
    paddingLeft: '27px',
    width: '750px',
    height: '33px',
  },
  wrap: {
    display: 'flex',
    alignItems: 'center',
    flexDirection: 'row',
    height: '33px',
  },
  subtract: { width: '10px', height: '13px' },
  FlipFlopsFill: { marginLeft: '5px', width: '25px', height: '12px' },
  FlipFlopsFill_2: { marginLeft: '2px', width: '25px', height: '12px' },
  chinaUnicom: {
    marginLeft: '5px',
    lineHeight: '32px',
    whiteSpace: 'nowrap',
    color: '#333333',
    fontSize: '23px',
    fontWeight: 400,
  },
  leftbariconmenber: { marginLeft: '9px', width: '24px', height: '19px' },
  wam: {
    marginLeft: '109px',
    lineHeight: '26px',
    whiteSpace: 'nowrap',
    color: '#333333',
    fontSize: '19px',
    fontWeight: 400,
  },
  block: {
    display: 'flex',
    alignItems: 'center',
    flexDirection: 'row',
    height: '33px',
  },
  lanya: { width: '15px', height: '26px' },
  percent: {
    marginLeft: '12px',
    lineHeight: '31px',
    whiteSpace: 'nowrap',
    color: '#333333',
    fontFamily: 'Rubik',
    fontSize: '24px',
    fontWeight: 400,
  },
  mark: { width: '49px', height: '21px' },
  bd: {
    display: 'flex',
    alignItems: 'center',
    flexDirection: 'row',
    marginTop: '20px',
    height: '50px',
  },
  icon: { marginTop: '3px', marginLeft: '31px', width: '21px', height: '39px' },
  registration: {
    marginLeft: '287px',
    maxWidth: '410px',
    height: '50px',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    lineHeight: '50px',
    whiteSpace: 'nowrap',
    color: '#333333',
    fontSize: '36px',
    fontWeight: 400,
  },
  submain: {
    display: 'flex',
    marginTop: '22px',
    backgroundColor: '#ffffff',
    width: '750px',
    height: '2px',
  },
  row: {
    marginTop: '24px',
    marginLeft: '28px',
    maxWidth: '722px',
    height: '45px',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    lineHeight: '45px',
    whiteSpace: 'nowrap',
    color: '#333333',
    fontSize: '32px',
    fontWeight: 400,
  },
  row1: {
    marginTop: '1px',
    marginLeft: '30px',
    maxWidth: '720px',
    height: '37px',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    lineHeight: '37px',
    whiteSpace: 'nowrap',
    color: '#999999',
    fontSize: '26px',
    fontWeight: 400,
  },
  row2: {
    display: 'flex',
    marginTop: '26px',
    backgroundColor: '#ffffff',
    width: '750px',
    height: '2px',
  },
  row3: {
    marginTop: '24px',
    marginLeft: '28px',
    maxWidth: '722px',
    height: '37px',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    lineHeight: '37px',
    whiteSpace: 'nowrap',
    color: '#999999',
    fontSize: '26px',
    fontWeight: 400,
  },
  row4: {
    marginTop: '20px',
    marginLeft: '29px',
    maxWidth: '721px',
    height: '42px',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    lineHeight: '42px',
    whiteSpace: 'nowrap',
    color: '#999999',
    fontSize: '30px',
    fontWeight: 400,
  },
  row5: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
    marginTop: '16px',
    width: '749px',
  },
  zhangYushengWrap: {
    display: 'flex',
    alignItems: 'center',
    flexDirection: 'row',
    borderRadius: '8px',
    backgroundColor: '#ffffff',
    width: '688px',
    height: '76px',
  },
  zhangYusheng: {
    marginLeft: '18px',
    lineHeight: '42px',
    whiteSpace: 'nowrap',
    color: '#333333',
    fontSize: '30px',
    fontWeight: 400,
  },
  row6: {
    marginTop: '28px',
    marginLeft: '29px',
    maxWidth: '721px',
    height: '42px',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    lineHeight: '42px',
    whiteSpace: 'nowrap',
    color: '#999999',
    fontSize: '30px',
    fontWeight: 400,
  },
  row7: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
    marginTop: '16px',
    width: '749px',
  },
  container: {
    display: 'flex',
    alignItems: 'center',
    flexDirection: 'row',
    borderRadius: '9px',
    backgroundColor: '#ffffff',
    width: '691px',
    height: '79px',
  },
  num: {
    marginLeft: '18px',
    lineHeight: '42px',
    whiteSpace: 'nowrap',
    color: '#333333',
    fontSize: '30px',
    fontWeight: 400,
  },
  row8: {
    marginTop: '25px',
    marginLeft: '29px',
    maxWidth: '721px',
    height: '42px',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    lineHeight: '42px',
    whiteSpace: 'nowrap',
    color: '#999999',
    fontSize: '30px',
    fontWeight: 400,
  },
  row9: {
    display: 'flex',
    position: 'relative',
    flexDirection: 'row',
    justifyContent: 'center',
    marginTop: '16px',
    width: '749px',
    height: '79px',
  },
  outer: {
    display: 'flex',
    alignItems: 'center',
    flexDirection: 'row',
    borderRadius: '9px',
    backgroundColor: '#ffffff',
    width: '691px',
    height: '79px',
  },
  word: {
    marginLeft: '17px',
    lineHeight: '42px',
    whiteSpace: 'nowrap',
    color: '#333333',
    fontSize: '30px',
    fontWeight: 400,
  },
  title: {
    position: 'absolute',
    top: '793px',
    left: '30px',
    lineHeight: '48px',
    whiteSpace: 'nowrap',
    color: '#f12d2d',
    fontSize: '34px',
    fontWeight: 400,
  },
  main: {
    marginTop: '54px',
    marginLeft: '29px',
    maxWidth: '721px',
    height: '42px',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    lineHeight: '42px',
    whiteSpace: 'nowrap',
    color: '#999999',
    fontSize: '30px',
    fontWeight: 400,
  },
  row10: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
    marginTop: '16px',
    width: '749px',
  },
  wrap_2: {
    display: 'flex',
    alignItems: 'center',
    flexDirection: 'row',
    borderRadius: '9px',
    backgroundColor: '#ffffff',
    width: '691px',
    height: '79px',
  },
  text: {
    marginLeft: '17px',
    lineHeight: '42px',
    whiteSpace: 'nowrap',
    color: '#333333',
    fontSize: '30px',
    fontWeight: 400,
  },
  row11: {
    marginTop: '25px',
    marginLeft: '29px',
    maxWidth: '721px',
    height: '42px',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    lineHeight: '42px',
    whiteSpace: 'nowrap',
    color: '#999999',
    fontSize: '30px',
    fontWeight: 400,
  },
  row12: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
    marginTop: '16px',
    width: '749px',
  },
  qcomWrap: {
    display: 'flex',
    alignItems: 'center',
    flexDirection: 'row',
    borderRadius: '9px',
    backgroundColor: '#ffffff',
    width: '691px',
    height: '79px',
  },
  qcom: {
    marginLeft: '17px',
    lineHeight: '45px',
    whiteSpace: 'nowrap',
    color: '#333333',
    fontSize: '32px',
    fontWeight: 400,
  },
  row13: { display: 'flex', flexDirection: 'row', marginTop: '4px' },
  txt: {
    marginLeft: '30px',
    width: '10px',
    height: '28px',
    lineHeight: '28px',
    whiteSpace: 'nowrap',
    color: '#f12d2d',
    fontSize: '20px',
    fontWeight: 400,
  },
  desc: {
    marginLeft: '7px',
    maxWidth: '702px',
    height: '28px',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    lineHeight: '28px',
    whiteSpace: 'nowrap',
    color: '#999999',
    fontSize: '20px',
    fontWeight: 400,
  },
  row14: {
    marginTop: '19px',
    marginLeft: '29px',
    maxWidth: '721px',
    height: '42px',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    lineHeight: '42px',
    whiteSpace: 'nowrap',
    color: '#999999',
    fontSize: '30px',
    fontWeight: 400,
  },
  row15: {
    display: 'flex',
    alignItems: 'center',
    flexDirection: 'row',
    marginTop: '19px',
    height: '36px',
  },
  backstageiconchose: { marginLeft: '50px', width: '27px', height: '27px' },
  iconTest: { marginLeft: '23px', width: '25px', height: '27px' },
  CenRadioHIcon: { marginLeft: '88px', width: '27px', height: '27px' },
  shanchu: {
    marginTop: '4px',
    marginLeft: '14px',
    width: '33px',
    height: '32px',
  },
  row16: {
    marginTop: '46px',
    marginLeft: '29px',
    maxWidth: '721px',
    height: '42px',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    lineHeight: '42px',
    whiteSpace: 'nowrap',
    color: '#999999',
    fontSize: '30px',
    fontWeight: 400,
  },
  row17: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
    marginTop: '16px',
    width: '749px',
  },
  group: {
    boxSizing: 'border-box',
    display: 'flex',
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    borderRadius: '9px',
    backgroundColor: '#ffffff',
    paddingRight: '13px',
    paddingLeft: '18px',
    width: '691px',
    height: '79px',
  },
  hanNationality: {
    width: '60px',
    height: '42px',
    lineHeight: '42px',
    whiteSpace: 'nowrap',
    color: '#333333',
    fontSize: '30px',
    fontWeight: 400,
  },
  down: { width: '21px', height: '11px' },
  row18: {
    marginTop: '25px',
    marginLeft: '29px',
    maxWidth: '721px',
    height: '42px',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    lineHeight: '42px',
    whiteSpace: 'nowrap',
    color: '#999999',
    fontSize: '30px',
    fontWeight: 400,
  },
  row19: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
    marginTop: '16px',
    width: '749px',
  },
  color: {
    borderRadius: '8px',
    backgroundColor: '#ffffff',
    width: '688px',
    height: '76px',
  },
  row20: {
    marginTop: '27px',
    marginLeft: '29px',
    maxWidth: '721px',
    height: '42px',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    lineHeight: '42px',
    whiteSpace: 'nowrap',
    color: '#999999',
    fontSize: '30px',
    fontWeight: 400,
  },
  row21: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
    marginTop: '17px',
    width: '749px',
  },
  colorDiv: {
    borderRadius: '8px',
    backgroundColor: '#ffffff',
    width: '688px',
    height: '76px',
  },
  row22: {
    marginTop: '28px',
    marginLeft: '29px',
    maxWidth: '721px',
    height: '42px',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    lineHeight: '42px',
    whiteSpace: 'nowrap',
    color: '#999999',
    fontSize: '30px',
    fontWeight: 400,
  },
  row23: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
    marginTop: '16px',
    width: '749px',
  },
  color_2: {
    borderRadius: '8px',
    backgroundColor: '#ffffff',
    width: '688px',
    height: '76px',
  },
  ft: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
    marginTop: '99px',
    width: '749px',
  },
  submitSaveWrap: {
    display: 'flex',
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'center',
    borderRadius: '44px',
    backgroundColor: '#2e8bff',
    width: '690px',
    height: '88px',
  },
  submitSave: {
    maxWidth: '678px',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    lineHeight: '48px',
    whiteSpace: 'nowrap',
    color: '#ffffff',
    fontSize: '34px',
    fontWeight: 400,
  },
};
